Repository gdscPre/Pre-client, pull requests merged in 2024-02, with the labels that each got.

#6 fix: 영양제 칸 개수 오류 수정
  src/pages/Signup/Signup.jsx
Labels: frontend

#8 Add files via upload
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/apis/dietAnalysis.js
  src/apis/foodList.js
  src/apis/foodRecord.js
  src/apis/foodSelect.js
  src/apis/login.js
  src/apis/mainpage.js
  src/apis/showSupplement.js
  src/apis/signUp.js
  src/apis/supplementCheck.js
  src/index.css
  src/index.js
  src/pages/Analysis/Analysis.jsx
  src/pages/Login/Login.css
  src/pages/Login/Login.jsx
  src/pages/Main/Main.css
  src/pages/Main/Main.jsx
  src/pages/Register/Register.jsx
  src/pages/Register/RegisterOwn.jsx
  src/pages/Signup/Signup.css
  src/pages/Signup/Signup.jsx
  src/pages/Supplement/Supplement.css
  src/pages/Supplement/Supplement.jsx
Labels: frontend

#7 feat: 마이페이지, 마이페이지 수정 기능 추가
  src/App.js
  src/Example3.js
  src/pages/Login/Login.css
  src/pages/Login/Login.jsx
  src/pages/Modify/Modify.css
  src/pages/Modify/Modify.jsx
  src/pages/Mypage/Mypage.css
  src/pages/Mypage/Mypage.jsx
  src/pages/Register/Register.jsx
  src/pages/Register/RegisterOwn.jsx
  src/pages/Signup/Signup.css
  src/pages/Signup/Signup.jsx
  src/pages/Supplement/Supplement.jsx
Labels: documentation, frontend, design, feat

#10 modify: 회원가입 기능 수정, UI 수정
  src/pages/Login/Login.css
  src/pages/Signup/Signup.css
  src/pages/Signup/Signup.jsx
Labels: frontend, design, modify
